return {
	KeyPrompts = {
		{ Key = "Three", Button = "Down", Position = UDim2.fromScale(0.675, 0.705), Index = 1 },
		{ Key = "Three", Button = "Down", Position = UDim2.fromScale(0.705, 0.705), Index = 1 },
		{ Key = "Four", Button = "Right", Position = UDim2.fromScale(0.735, 0.705), Index = 1 },
		{ Key = "One", Button = "Up", Position = UDim2.fromScale(0.765, 0.705), Index = 1 },
	},
	[[                                      Tuesday, Apr 22
    
I lost the code again. <font color="rgb(150,150,150)">2:11 AM</font>

                                                                     You're kidding me.

Can you just give it to me please.

Last time, I promise.

                                       <font color="rgb(150,150,150)">3:01 AM</font> Last time. This is a security risk.

                                                                The code is]],
}
