return {
	KeyPrompts = {
		{ Key = "Three", Button = "DPadDown", Position = UDim2.fromScale(0.832, 0.74), Index = 1 },
		{ Key = "Three", Button = "DPadDown", Position = UDim2.fromScale(0.861, 0.74), Index = 1 },
		{ Key = "Four", Button = "DPadRight", Position = UDim2.fromScale(0.89, 0.74), Index = 1 },
		{ Key = "One", Button = "DPadUp", Position = UDim2.fromScale(0.92, 0.74), Index = 1 },
	},
	[[                                      			Tuesday, Apr 22
    
I lost the code again. <font color="rgb(150,150,150)">2:11 AM</font>

                                                                    						 You're kidding me.

Can you just give it to me please.

Last time, I promise.

                                    						   <font color="rgb(150,150,150)">3:01 AM</font> Last time. This is a security risk.

                                                            						    The code is]],
}
