return {

	KeyPrompts = {
		{ Key = "LeftShift", Button = "ButtonR2", Position = UDim2.fromScale(0, 0.5), Index = 2 },
	},

	[[Rationing means a fair share for all of us.]],
	[[<font color="#FF7800">Hunger:</font>
	
Over time your hunger will, very slowly, run out. Eat food found around the map to regain hunger.

	 to run.

Running will increase the rate at which you lose hunger.

If your hunger reaches 0, you will take more damage, and won't be able to run.]],
}
