local UIController = {}

--// Services
local ReplicatedStorage = game:GetService("ReplicatedStorage")

--// Instances

--// Modules
local Fusion = require(ReplicatedStorage.Packages.Fusion)

--// Values

--// Functions
function UIController:Init()
	--Prestart Code
end

function UIController:Start()
	--Start Code
end

function UIController:Load()
	--Start Code
end

--// Main //--
return UIController
